// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: spotify.proto

package spotify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpotifySearch_GetTracksWithFeatures_FullMethodName = "/spotify.SpotifySearch/GetTracksWithFeatures"
)

// SpotifySearchClient is the client API for SpotifySearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpotifySearch is the gRPC service for fetching tracks with embeddings.
type SpotifySearchClient interface {
	GetTracksWithFeatures(ctx context.Context, in *GetTracksWithFeaturesRequest, opts ...grpc.CallOption) (*GetTracksWithFeaturesResponse, error)
}

type spotifySearchClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotifySearchClient(cc grpc.ClientConnInterface) SpotifySearchClient {
	return &spotifySearchClient{cc}
}

func (c *spotifySearchClient) GetTracksWithFeatures(ctx context.Context, in *GetTracksWithFeaturesRequest, opts ...grpc.CallOption) (*GetTracksWithFeaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTracksWithFeaturesResponse)
	err := c.cc.Invoke(ctx, SpotifySearch_GetTracksWithFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpotifySearchServer is the server API for SpotifySearch service.
// All implementations must embed UnimplementedSpotifySearchServer
// for forward compatibility.
//
// SpotifySearch is the gRPC service for fetching tracks with embeddings.
type SpotifySearchServer interface {
	GetTracksWithFeatures(context.Context, *GetTracksWithFeaturesRequest) (*GetTracksWithFeaturesResponse, error)
	mustEmbedUnimplementedSpotifySearchServer()
}

// UnimplementedSpotifySearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpotifySearchServer struct{}

func (UnimplementedSpotifySearchServer) GetTracksWithFeatures(context.Context, *GetTracksWithFeaturesRequest) (*GetTracksWithFeaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTracksWithFeatures not implemented")
}
func (UnimplementedSpotifySearchServer) mustEmbedUnimplementedSpotifySearchServer() {}
func (UnimplementedSpotifySearchServer) testEmbeddedByValue()                       {}

// UnsafeSpotifySearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpotifySearchServer will
// result in compilation errors.
type UnsafeSpotifySearchServer interface {
	mustEmbedUnimplementedSpotifySearchServer()
}

func RegisterSpotifySearchServer(s grpc.ServiceRegistrar, srv SpotifySearchServer) {
	// If the following call panics, it indicates UnimplementedSpotifySearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpotifySearch_ServiceDesc, srv)
}

func _SpotifySearch_GetTracksWithFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTracksWithFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifySearchServer).GetTracksWithFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotifySearch_GetTracksWithFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifySearchServer).GetTracksWithFeatures(ctx, req.(*GetTracksWithFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpotifySearch_ServiceDesc is the grpc.ServiceDesc for SpotifySearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpotifySearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spotify.SpotifySearch",
	HandlerType: (*SpotifySearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTracksWithFeatures",
			Handler:    _SpotifySearch_GetTracksWithFeatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spotify.proto",
}
