// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spotify.proto

package spotify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTracksWithFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackIds      []string               `protobuf:"bytes,1,rep,name=track_ids,json=trackIds,proto3" json:"track_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksWithFeaturesRequest) Reset() {
	*x = GetTracksWithFeaturesRequest{}
	mi := &file_spotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksWithFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksWithFeaturesRequest) ProtoMessage() {}

func (x *GetTracksWithFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksWithFeaturesRequest.ProtoReflect.Descriptor instead.
func (*GetTracksWithFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_spotify_proto_rawDescGZIP(), []int{0}
}

func (x *GetTracksWithFeaturesRequest) GetTrackIds() []string {
	if x != nil {
		return x.TrackIds
	}
	return nil
}

type TrackWithFeatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackWithFeatures) Reset() {
	*x = TrackWithFeatures{}
	mi := &file_spotify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackWithFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackWithFeatures) ProtoMessage() {}

func (x *TrackWithFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackWithFeatures.ProtoReflect.Descriptor instead.
func (*TrackWithFeatures) Descriptor() ([]byte, []int) {
	return file_spotify_proto_rawDescGZIP(), []int{1}
}

func (x *TrackWithFeatures) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrackWithFeatures) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *TrackWithFeatures) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetTracksWithFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackWithFeatures   `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksWithFeaturesResponse) Reset() {
	*x = GetTracksWithFeaturesResponse{}
	mi := &file_spotify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksWithFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksWithFeaturesResponse) ProtoMessage() {}

func (x *GetTracksWithFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksWithFeaturesResponse.ProtoReflect.Descriptor instead.
func (*GetTracksWithFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_spotify_proto_rawDescGZIP(), []int{2}
}

func (x *GetTracksWithFeaturesResponse) GetTracks() []*TrackWithFeatures {
	if x != nil {
		return x.Tracks
	}
	return nil
}

var File_spotify_proto protoreflect.FileDescriptor

const file_spotify_proto_rawDesc = "" +
	"\n" +
	"\rspotify.proto\x12\aspotify\";\n" +
	"\x1cGetTracksWithFeaturesRequest\x12\x1b\n" +
	"\ttrack_ids\x18\x01 \x03(\tR\btrackIds\"\xc4\x01\n" +
	"\x11TrackWithFeatures\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.spotify.TrackWithFeatures.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x1dGetTracksWithFeaturesResponse\x122\n" +
	"\x06tracks\x18\x01 \x03(\v2\x1a.spotify.TrackWithFeaturesR\x06tracks2w\n" +
	"\rSpotifySearch\x12f\n" +
	"\x15GetTracksWithFeatures\x12%.spotify.GetTracksWithFeaturesRequest\x1a&.spotify.GetTracksWithFeaturesResponseB=Z;github.com/music-recommender/internal/proto/spotify;spotifyb\x06proto3"

var (
	file_spotify_proto_rawDescOnce sync.Once
	file_spotify_proto_rawDescData []byte
)

func file_spotify_proto_rawDescGZIP() []byte {
	file_spotify_proto_rawDescOnce.Do(func() {
		file_spotify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_proto_rawDesc), len(file_spotify_proto_rawDesc)))
	})
	return file_spotify_proto_rawDescData
}

var file_spotify_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spotify_proto_goTypes = []any{
	(*GetTracksWithFeaturesRequest)(nil),  // 0: spotify.GetTracksWithFeaturesRequest
	(*TrackWithFeatures)(nil),             // 1: spotify.TrackWithFeatures
	(*GetTracksWithFeaturesResponse)(nil), // 2: spotify.GetTracksWithFeaturesResponse
	nil,                                   // 3: spotify.TrackWithFeatures.MetadataEntry
}
var file_spotify_proto_depIdxs = []int32{
	3, // 0: spotify.TrackWithFeatures.metadata:type_name -> spotify.TrackWithFeatures.MetadataEntry
	1, // 1: spotify.GetTracksWithFeaturesResponse.tracks:type_name -> spotify.TrackWithFeatures
	0, // 2: spotify.SpotifySearch.GetTracksWithFeatures:input_type -> spotify.GetTracksWithFeaturesRequest
	2, // 3: spotify.SpotifySearch.GetTracksWithFeatures:output_type -> spotify.GetTracksWithFeaturesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spotify_proto_init() }
func file_spotify_proto_init() {
	if File_spotify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_proto_rawDesc), len(file_spotify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spotify_proto_goTypes,
		DependencyIndexes: file_spotify_proto_depIdxs,
		MessageInfos:      file_spotify_proto_msgTypes,
	}.Build()
	File_spotify_proto = out.File
	file_spotify_proto_goTypes = nil
	file_spotify_proto_depIdxs = nil
}
